package treptowkolleg.tests;

import treptowkolleg.core.Database;
import treptowkolleg.core.IOApplication;
import treptowkolleg.extension.Session;
import treptowkolleg.model.db.Command;
import treptowkolleg.model.orm.*;
import treptowkolleg.model.session.Property;
import treptowkolleg.tests.entity.User;

import java.lang.reflect.Field;
import java.sql.Connection;
import java.util.StringJoiner;

public class MySQLTest extends IOApplication {
    public static void main(String[] args) {
        new MySQLTest();
    }

    @Override
    public void run() {
        Connection connection = Database.connect();

        if (null == connection) {
            System.exit(1);
        }
        println(Session.get(Property.CONNECTION));
        print(mapToTable(User.class));
    }

    public String mapToTable(Class<?> entityClass) {
        if (!entityClass.isAnnotationPresent(Entity.class)) {
            throw new IllegalArgumentException("Keine ORM-Entität: " + entityClass);
        }
        String tableName = ORMUtils.toSnakeTail(entityClass.getSimpleName());
        StringJoiner columns = new StringJoiner(", ");

        for (Field field : entityClass.getDeclaredFields()) {
            StringBuilder column = new StringBuilder();

            if (field.isAnnotationPresent(PrimaryKey.class)) {
                PrimaryKey pk = field.getAnnotation(PrimaryKey.class);
                String colName = ORMUtils.toSnakeTail(field.getName());
                String sqlType = ORMUtils.toSqlType(field);

                column.append(colName)
                        .append(" ")
                        .append(sqlType)
                        .append(Command.PRIMARY_KEY);
                if(pk.autoGenerated()) {
                    column.append(Command.AUTO_INCREMENT);
                }
                columns.add(column);
            } else if (field.isAnnotationPresent(Column.class)) {
                Column ormColumn = field.getAnnotation(Column.class);
                String colName = ORMUtils.toSnakeTail(field.getName());
                String sqlType = ORMUtils.toSqlType(field);

                column.append(colName)
                        .append(" ")
                        .append(sqlType);
                if(!ormColumn.nullable()) {
                    column.append(Command.NOT_NULL);
                }
                columns.add(column);
            }
        }
        return Command.CREATE_TABLE_IF_NOT_EXISTS
                + tableName
                + Command.OPEN_PAREN
                + columns
                + Command.CLOSE_PAREN
                + Command.SEMICOLON;
    }
}
